package:
  name: menpofit
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - cython 0.23.*

  run:
    - python
    - menpo 0.7.*
    - scikit-learn >=0.16
    - dlib >=18.18
    - pandas >=0.16

test:
  requires:
    - nose
    - mock

  imports:
    - menpofit

about:
  home: https://github.com/menpo/menpofit/
  license: BSD
