name: menpofit_rtd
channels:
  - menpo
dependencies:
  - python
  - setuptools

  - menpo>=0.6,<0.7
  - scikit-learn>=0.17,<0.18
  - pandas>=0.17,<0.18
  - mock=1.3.*
  - nose
  - pip:
      - sphinx==1.3.1
      - sphinx_rtd_theme==0.1.7
      - sphinxmapxrefrole==0.2.1

